export const courses = [
  // Web Development Courses
  {
    title: 'React for Beginners',
    description: 'Learn the basics of React and build your first application.',
    image: '',
    courseId: 'react-for-beginners',
    duration: '6 weeks',
    ratings: 4.5,
    category: 'Web Development',
    difficulty: 'Beginner',
    tags: ['JavaScript', 'React'],
    syllabus: [
      {
        title: 'Chapter 1: Introduction to React',
        content: 'Learn about the basics of React and why it is popular.',
        lectures: 3,
        time: '2 hours',
        subtopics: ['What is React?', 'History of React', 'Why use React?'],
      },
      {
        title: 'Chapter 2: Components and Props',
        content: 'Understand components and how to use props in React.',
        lectures: 4,
        time: '3 hours',
        subtopics: ['Functional Components', 'Class Components', 'Using Props'],
      },
      {
        title: 'Chapter 3: State and Lifecycle',
        content: 'Learn about state and the component lifecycle in React.',
        lectures: 5,
        time: '4 hours',
        subtopics: ['State Basics', 'Lifecycle Methods', 'State Management'],
      },
    ],
    format: 'Video lectures, hands-on projects, quizzes',
    reviews: [
      { rating: 5, comment: 'Great introduction to React!' },
      { rating: 4, comment: 'Very informative, but could use more examples.' },
    ],
    certificates: true,
    faqs: [
      { question: 'Do I need prior programming experience?', answer: 'Basic knowledge of JavaScript is recommended.' },
      { question: 'Will I get a certificate?', answer: 'Yes, you will receive a certificate upon completion.' },
    ],
    media: [
      'https://images.unsplash.com/photo-1559163499-413811fb2345?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1573496780727-e2f4e91424e2?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80',
    ],
  },
  {
    title: 'Advanced CSS Techniques',
    description: 'Master advanced CSS concepts and techniques.',
    image: 'https://plus.unsplash.com/premium_photo-1685086785636-2a1a0e5b591f?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTN8fGNzc3xlbnwwfHwwfHx8MA%3D%3D',
    courseId: 'advanced-css-techniques',
    duration: '4 weeks',
    ratings: 4.8,
    category: 'Web Development',
    difficulty: 'Intermediate',
    tags: ['CSS', 'Web Design'],
    syllabus: [
      {
        title: 'Chapter 1: CSS Grid Layout',
        content: 'Learn about CSS Grid Layout and its applications.',
        lectures: 3,
        time: '2 hours',
        subtopics: ['Grid Basics', 'Creating Grid Layouts', 'Responsive Design with Grid'],
      },
      {
        title: 'Chapter 2: Flexbox',
        content: 'Understand Flexbox and how to use it for layout design.',
        lectures: 4,
        time: '3 hours',
        subtopics: ['Flexbox Basics', 'Aligning Items', 'Responsive Design with Flexbox'],
      },
      {
        title: 'Chapter 3: Animations and Transitions',
        content: 'Learn how to create animations and transitions using CSS.',
        lectures: 5,
        time: '4 hours',
        subtopics: ['Keyframes', 'Transition Properties', 'Animation Timing Functions'],
      },
    ],
    format: 'Video lectures, hands-on projects, quizzes',
    reviews: [
      { rating: 5, comment: 'Best course on advanced CSS I have taken!' },
      { rating: 4, comment: 'Very detailed and well-structured.' },
    ],
    certificates: true,
    faqs: [
      { question: 'Do I need prior knowledge of CSS?', answer: 'Basic CSS knowledge is required.' },
      { question: 'Is this course suitable for beginners?', answer: 'This course is for intermediate learners.' },
    ],
    media: [
      'https://images.unsplash.com/photo-1521791055366-0d553872125f?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1580910051071-73e9c3e18fdc?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80',
    ],
  },
  {
    title: 'Full-Stack Web Development',
    description: 'Become a full-stack web developer with this comprehensive course.',
    image: 'https://images.unsplash.com/photo-1545670723-196ed0954986?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTl8fHdlYiUyMGRldmVsb3BtZW50fGVufDB8fDB8fHww',
    courseId: 'full-stack-web-development',
    duration: '12 weeks',
    ratings: 4.9,
    category: 'Web Development',
    difficulty: 'Advanced',
    tags: ['JavaScript', 'Node.js', 'React', 'CSS', 'HTML'],
    syllabus: [
      {
        title: 'Module 1: Frontend Development',
        content: 'Learn about HTML, CSS, and JavaScript for frontend development.',
        lectures: 6,
        time: '5 hours',
        subtopics: ['HTML5', 'CSS3', 'JavaScript ES6'],
      },
      {
        title: 'Module 2: Backend Development',
        content: 'Understand backend development using Node.js and Express.',
        lectures: 7,
        time: '6 hours',
        subtopics: ['Node.js Basics', 'Express Framework', 'Database Integration'],
      },
      {
        title: 'Module 3: Full-Stack Integration',
        content: 'Learn how to integrate frontend and backend to build full-stack applications.',
        lectures: 8,
        time: '7 hours',
        subtopics: ['REST APIs', 'React with Node.js', 'Deployment Strategies'],
      },
    ],
    format: 'Video lectures, hands-on projects, quizzes',
    reviews: [
      { rating: 5, comment: 'A complete course for aspiring full-stack developers!' },
      { rating: 4.5, comment: 'Excellent content and projects.' },
    ],
    certificates: true,
    faqs: [
      { question: 'Do I need prior programming experience?', answer: 'Basic knowledge of JavaScript is recommended.' },
      { question: 'Will I get a certificate?', answer: 'Yes, you will receive a certificate upon completion.' },
    ],
    media: [
      'https://images.unsplash.com/photo-1515879218367-8466d910aaa4?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1590642914884-9d79da91e065?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80',
    ],
  },

  // Computer Science Courses
  {
    title: 'Introduction to Algorithms',
    description: 'Learn the fundamental algorithms in computer science.',
    image: 'https://images.unsplash.com/photo-1519985176271-adb1088fa94c?ixlib=rb-1.2.1&auto=format&fit=crop&w=400&q=80',
    courseId: 'introduction-to-algorithms',
    duration: '8 weeks',
    ratings: 4.7,
    category: 'Computer Science',
    difficulty: 'Intermediate',
    tags: ['Algorithms', 'Data Structures', 'Computer Science'],
    syllabus: [
      {
        title: 'Week 1: Sorting Algorithms',
        content: 'Learn about various sorting algorithms and their complexities.',
        lectures: 4,
        time: '3 hours',
        subtopics: ['Bubble Sort', 'Merge Sort', 'Quick Sort'],
      },
      {
        title: 'Week 2: Searching Algorithms',
        content: 'Understand different searching algorithms.',
        lectures: 3,
        time: '2 hours',
        subtopics: ['Linear Search', 'Binary Search'],
      },
      {
        title: 'Week 3: Graph Algorithms',
        content: 'Explore algorithms related to graphs.',
        lectures: 5,
        time: '4 hours',
        subtopics: ['Dijkstra’s Algorithm', 'A* Search'],
      },
    ],
    format: 'Video lectures, hands-on projects, quizzes',
    reviews: [
      { rating: 5, comment: 'Very detailed and clear explanations!' },
      { rating: 4, comment: 'A great refresher on algorithms.' },
    ],
    certificates: true,
    faqs: [
      { question: 'Do I need prior programming experience?', answer: 'Basic knowledge of programming is required.' },
      { question: 'Will I get a certificate?', answer: 'Yes, you will receive a certificate upon completion.' },
    ],
    media: [
      'https://images.unsplash.com/photo-1526374959541-a071d58b56a2?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1515879218367-8466d910aaa4?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80',
    ],
  },
  {
    title: 'Data Structures in Depth',
    description: 'Master data structures to enhance your programming skills.',
    image: 'https://images.unsplash.com/photo-1534751516642-a1af1ef63e',
    courseId: 'data-structures-in-depth',
    duration: '6 weeks',
    ratings: 4.6,
    category: 'Computer Science',
    difficulty: 'Intermediate',
    tags: ['Data Structures', 'Algorithms', 'Programming'],
    syllabus: [
      {
        title: 'Week 1: Arrays and Linked Lists',
        content: 'Learn about arrays, linked lists, and their implementations.',
        lectures: 3,
        time: '2 hours',
        subtopics: ['Arrays', 'Singly Linked Lists', 'Doubly Linked Lists'],
      },
      {
        title: 'Week 2: Stacks and Queues',
        content: 'Understand the concepts of stacks and queues and their applications.',
        lectures: 4,
        time: '3 hours',
        subtopics: ['Stacks', 'Queues', 'Implementations and Applications'],
      },
      {
        title: 'Week 3: Trees and Graphs',
        content: 'Explore tree and graph data structures and their algorithms.',
        lectures: 5,
        time: '4 hours',
        subtopics: ['Binary Trees', 'Graph Representation', 'Traversal Algorithms'],
      },
    ],
    format: 'Video lectures, coding exercises, quizzes',
    reviews: [
      { rating: 5, comment: 'In-depth coverage of data structures with clear examples!' },
      { rating: 4.5, comment: 'Excellent course material and challenging exercises.' },
    ],
    certificates: true,
    faqs: [
      { question: 'Is this course suitable for beginners?', answer: 'This course is recommended for intermediate learners with some programming experience.' },
      { question: 'Will I receive a certificate?', answer: 'Yes, upon successful completion of the course.' },
    ],
    media: [
      'https://images.unsplash.com/photo-1522196772883-39f0a118be96?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1532009324734-20a7a5813719?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80',
    ],
  },
];
